from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from src.librarian.graph.exporters import graph_to_payload


def export_cypher(graph, root: str | Path) -> Path:
    output_path = Path(root).resolve() / ".librarian" / "graph.cypher"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "// Generated by The Librarian. Review before importing into Neo4j.",
        "CREATE CONSTRAINT librarian_node_id IF NOT EXISTS FOR (n:LibrarianNode) REQUIRE n.id IS UNIQUE;",
        "",
    ]
    payload = graph_to_payload(graph)
    for node in payload.nodes:
        label = _label(node.type)
        lines.append(f'MERGE (n:LibrarianNode:{label} {{id: {_string(node.id)}}})')
        lines.append(
            "SET n.label = "
            + _string(node.label)
            + ", n.type = "
            + _string(node.type)
            + ", n.properties = "
            + _string(json.dumps(node.properties, sort_keys=True, ensure_ascii=False))
            + ";"
        )
        lines.append("")
    for edge in payload.edges:
        relation = _label(edge.type).upper()
        lines.append(f"MATCH (a:LibrarianNode {{id: {_string(edge.source)}}}), (b:LibrarianNode {{id: {_string(edge.target)}}})")
        lines.append(f"MERGE (a)-[r:{relation}]->(b)")
        lines.append(
            "SET r.confidence = "
            + str(float(edge.confidence))
            + ", r.reason = "
            + _string(edge.reason)
            + ", r.properties = "
            + _string(json.dumps(edge.properties, sort_keys=True, ensure_ascii=False))
            + ";"
        )
        lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def _label(value: str) -> str:
    label = re.sub(r"[^A-Za-z0-9_]", "_", value or "Node")
    if not label or label[0].isdigit():
        label = f"Node_{label}"
    return label


def _string(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n")
    return f'"{text}"'
